modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Shoxie12/Audiocassettes/issues"
license="LGPL License"
[[mods]]
modId="audiocassettes"
version="1.1"
displayName="Audio Cassettes"
displayURL="https://www.curseforge.com/minecraft/mc-mods/audiocassettes"
credits="Thanks to McJty, Kenny Tutorials and many many other for their modding tutorials! This mod is partically based on Walkman by AshIndigo"
authors="Shoxie"
description='''
This mod adds an audiocassettes.
...
'''